import {metricsToAudits} from 'lighthouse/core/config/metrics-to-audits.js';
import Result from 'lighthouse/types/lhr/lhr.js';

export default {
  extends: 'lighthouse:default',
  categories: {
    performance: {
      title: 'Performance',
      supportedModes: [
        'navigation',
        'timespan',
        'snapshot',
      ] as Result.GatherMode[],
      auditRefs: [
        {
          id: 'first-contentful-paint',
          weight: 10,
          group: 'metrics',
          acronym: 'FCP',
          relevantAudits: metricsToAudits.fcpRelevantAudits,
        },
        {
          id: 'largest-contentful-paint',
          weight: 25,
          group: 'metrics',
          acronym: 'LCP',
          relevantAudits: metricsToAudits.lcpRelevantAudits,
        },
        {
          id: 'total-blocking-time',
          weight: 30,
          group: 'metrics',
          acronym: 'TBT',
          relevantAudits: metricsToAudits.tbtRelevantAudits,
        },
        {
          id: 'cumulative-layout-shift',
          weight: 25,
          group: 'metrics',
          acronym: 'CLS',
          relevantAudits: metricsToAudits.clsRelevantAudits,
        },
        {id: 'speed-index', weight: 10, group: 'metrics', acronym: 'SI'},
        {
          id: 'interaction-to-next-paint',
          weight: 0,
          group: 'metrics',
          acronym: 'INP',
          relevantAudits: metricsToAudits.inpRelevantAudits,
        },

        // These are our "invisible" metrics. Not displayed, but still in the LHR.
        {id: 'interactive', weight: 0, group: 'hidden', acronym: 'TTI'},
        {id: 'max-potential-fid', weight: 0, group: 'hidden'},
        {
          id: 'first-meaningful-paint',
          weight: 0,
          acronym: 'FMP',
          group: 'hidden',
        },

        // These audits will be put in "load-opportunities" or "diagnostics" based on their details type.
        {id: 'render-blocking-resources', weight: 0},
        {id: 'uses-responsive-images', weight: 0},
        {id: 'offscreen-images', weight: 0},
        {id: 'unminified-css', weight: 0},
        {id: 'unminified-javascript', weight: 0},
        {id: 'unused-css-rules', weight: 0},
        {id: 'unused-javascript', weight: 0},
        {id: 'uses-optimized-images', weight: 0},
        {id: 'modern-image-formats', weight: 0},
        {id: 'uses-text-compression', weight: 0},
        {id: 'uses-rel-preconnect', weight: 0},
        {id: 'server-response-time', weight: 0},
        {id: 'redirects', weight: 0},
        {id: 'uses-rel-preload', weight: 0},
        {id: 'uses-http2', weight: 0},
        {id: 'efficient-animated-content', weight: 0},
        {id: 'duplicated-javascript', weight: 0},
        {id: 'legacy-javascript', weight: 0},
        {id: 'prioritize-lcp-image', weight: 0},
        {id: 'total-byte-weight', weight: 0},
        {id: 'uses-long-cache-ttl', weight: 0},
        {id: 'dom-size', weight: 0},
        {id: 'critical-request-chains', weight: 0},
        {id: 'user-timings', weight: 0},
        {id: 'bootup-time', weight: 0},
        {id: 'mainthread-work-breakdown', weight: 0},
        {id: 'font-display', weight: 0},
        {id: 'third-party-summary', weight: 0},
        {id: 'third-party-facades', weight: 0},
        {id: 'largest-contentful-paint-element', weight: 0},
        {id: 'lcp-lazy-loaded', weight: 0},
        {id: 'layout-shifts', weight: 0},
        {id: 'uses-passive-event-listeners', weight: 0},
        {id: 'no-document-write', weight: 0},
        {id: 'long-tasks', weight: 0},
        {id: 'non-composited-animations', weight: 0},
        {id: 'unsized-images', weight: 0},
        {id: 'viewport', weight: 0},
        {id: 'uses-responsive-images-snapshot', weight: 0},
        {id: 'work-during-interaction', weight: 0},
        {id: 'bf-cache', weight: 0},

        // Budget audits.
        {id: 'performance-budget', weight: 0, group: 'budgets'},
        {id: 'timing-budget', weight: 0, group: 'budgets'},

        // Audits past this point contain useful data but are not displayed with other audits.
        {id: 'network-requests', weight: 0, group: 'hidden'},
        {id: 'network-rtt', weight: 0, group: 'hidden'},
        {id: 'network-server-latency', weight: 0, group: 'hidden'},
        {id: 'main-thread-tasks', weight: 0, group: 'hidden'},
        {id: 'diagnostics', weight: 0, group: 'hidden'},
        {id: 'metrics', weight: 0, group: 'hidden'},
        {id: 'screenshot-thumbnails', weight: 0, group: 'hidden'},
        {id: 'final-screenshot', weight: 0, group: 'hidden'},
        {id: 'script-treemap-data', weight: 0, group: 'hidden'},
        {id: 'resource-summary', weight: 0, group: 'hidden'},
        {id: 'layout-shift-elements', weight: 0, group: 'hidden'},
      ],
    },
    accessibility: {
      title: 'Accessibility',
      // TODO copy or adapt these descriptions
      // description: str_(UIStrings.a11yCategoryDescription),
      // manualDescription: str_(UIStrings.a11yCategoryManualDescription),
      supportedModes: ['navigation', 'snapshot'] as Result.GatherMode[],
      // Audit weights are meant to match the aXe scoring system of
      // minor, moderate, serious, and critical.
      // See the audits listed at dequeuniversity.com/rules/axe/4.7.
      // Click on an audit and check the right hand column to see its severity.
      auditRefs: [
        {id: 'accesskeys', weight: 7, group: 'a11y-navigation'},
        {id: 'aria-allowed-attr', weight: 10, group: 'a11y-aria'},
        {id: 'aria-allowed-role', weight: 1, group: 'a11y-aria'},
        {id: 'aria-command-name', weight: 7, group: 'a11y-aria'},
        {id: 'aria-dialog-name', weight: 7, group: 'a11y-aria'},
        {id: 'aria-hidden-body', weight: 10, group: 'a11y-aria'},
        {id: 'aria-hidden-focus', weight: 7, group: 'a11y-aria'},
        {id: 'aria-input-field-name', weight: 7, group: 'a11y-aria'},
        {id: 'aria-meter-name', weight: 7, group: 'a11y-aria'},
        {id: 'aria-progressbar-name', weight: 7, group: 'a11y-aria'},
        {id: 'aria-required-attr', weight: 10, group: 'a11y-aria'},
        {id: 'aria-required-children', weight: 10, group: 'a11y-aria'},
        {id: 'aria-required-parent', weight: 10, group: 'a11y-aria'},
        {id: 'aria-roles', weight: 7, group: 'a11y-aria'},
        {id: 'aria-text', weight: 7, group: 'a11y-aria'},
        {id: 'aria-toggle-field-name', weight: 7, group: 'a11y-aria'},
        {id: 'aria-tooltip-name', weight: 7, group: 'a11y-aria'},
        {id: 'aria-treeitem-name', weight: 7, group: 'a11y-aria'},
        {id: 'aria-valid-attr-value', weight: 10, group: 'a11y-aria'},
        {id: 'aria-valid-attr', weight: 10, group: 'a11y-aria'},
        {id: 'button-name', weight: 10, group: 'a11y-names-labels'},
        {id: 'bypass', weight: 7, group: 'a11y-navigation'},
        {id: 'color-contrast', weight: 7, group: 'a11y-color-contrast'},
        {id: 'definition-list', weight: 7, group: 'a11y-tables-lists'},
        {id: 'dlitem', weight: 7, group: 'a11y-tables-lists'},
        {id: 'document-title', weight: 7, group: 'a11y-names-labels'},
        {id: 'duplicate-id-active', weight: 7, group: 'a11y-navigation'},
        {id: 'duplicate-id-aria', weight: 10, group: 'a11y-aria'},
        {
          id: 'form-field-multiple-labels',
          weight: 3,
          group: 'a11y-names-labels',
        },
        {id: 'frame-title', weight: 7, group: 'a11y-names-labels'},
        {id: 'heading-order', weight: 3, group: 'a11y-navigation'},
        {id: 'html-has-lang', weight: 7, group: 'a11y-language'},
        {id: 'html-lang-valid', weight: 7, group: 'a11y-language'},
        {id: 'html-xml-lang-mismatch', weight: 3, group: 'a11y-language'},
        {id: 'image-alt', weight: 10, group: 'a11y-names-labels'},
        {id: 'image-redundant-alt', weight: 1, group: 'a11y-names-labels'},
        {id: 'input-button-name', weight: 10, group: 'a11y-names-labels'},
        {id: 'input-image-alt', weight: 10, group: 'a11y-names-labels'},
        {id: 'label', weight: 7, group: 'a11y-names-labels'},
        {id: 'link-in-text-block', weight: 7, group: 'a11y-color-contrast'},
        {id: 'link-name', weight: 7, group: 'a11y-names-labels'},
        {id: 'list', weight: 7, group: 'a11y-tables-lists'},
        {id: 'listitem', weight: 7, group: 'a11y-tables-lists'},
        {id: 'meta-refresh', weight: 10, group: 'a11y-best-practices'},
        {id: 'meta-viewport', weight: 10, group: 'a11y-best-practices'},
        {id: 'object-alt', weight: 7, group: 'a11y-names-labels'},
        {id: 'select-name', weight: 7, group: 'a11y-names-labels'},
        {id: 'skip-link', weight: 3, group: 'a11y-names-labels'},
        {id: 'tabindex', weight: 7, group: 'a11y-navigation'},
        {id: 'table-duplicate-name', weight: 1, group: 'a11y-tables-lists'},
        {id: 'td-headers-attr', weight: 7, group: 'a11y-tables-lists'},
        {id: 'th-has-data-cells', weight: 7, group: 'a11y-tables-lists'},
        {id: 'valid-lang', weight: 7, group: 'a11y-language'},
        {id: 'video-caption', weight: 10, group: 'a11y-audio-video'},
        // Manual audits
        {id: 'focusable-controls', weight: 0},
        {id: 'interactive-element-affordance', weight: 0},
        {id: 'logical-tab-order', weight: 0},
        {id: 'visual-order-follows-dom', weight: 0},
        {id: 'focus-traps', weight: 0},
        {id: 'managed-focus', weight: 0},
        {id: 'use-landmarks', weight: 0},
        {id: 'offscreen-content-hidden', weight: 0},
        {id: 'custom-controls-labels', weight: 0},
        {id: 'custom-controls-roles', weight: 0},
        // Hidden audits
        {id: 'empty-heading', weight: 0, group: 'hidden'},
        {id: 'identical-links-same-purpose', weight: 0, group: 'hidden'},
        {id: 'landmark-one-main', weight: 0, group: 'hidden'},
        {id: 'target-size', weight: 0, group: 'hidden'},
        {id: 'label-content-name-mismatch', weight: 0, group: 'hidden'},
        {id: 'table-fake-caption', weight: 0, group: 'hidden'},
        {id: 'td-has-header', weight: 0, group: 'hidden'},
      ],
    },
    'best-practices': {
      title: 'Best Practices',
      supportedModes: [
        'navigation',
        'timespan',
        'snapshot',
      ] as Result.GatherMode[],
      auditRefs: [
        // Trust & Safety
        {id: 'is-on-https', weight: 5, group: 'best-practices-trust-safety'},
        {
          id: 'geolocation-on-start',
          weight: 1,
          group: 'best-practices-trust-safety',
        },
        {
          id: 'notification-on-start',
          weight: 1,
          group: 'best-practices-trust-safety',
        },
        {id: 'csp-xss', weight: 0, group: 'best-practices-trust-safety'},
        // User Experience
        {
          id: 'paste-preventing-inputs',
          weight: 3,
          group: 'best-practices-ux',
        },
        {id: 'image-aspect-ratio', weight: 1, group: 'best-practices-ux'},
        {id: 'image-size-responsive', weight: 1, group: 'best-practices-ux'},
        {id: 'preload-fonts', weight: 1, group: 'best-practices-ux'},
        // Browser Compatibility
        {id: 'doctype', weight: 1, group: 'best-practices-browser-compat'},
        {id: 'charset', weight: 1, group: 'best-practices-browser-compat'},
        // General Group
        {
          id: 'no-unload-listeners',
          weight: 1,
          group: 'best-practices-general',
        },
        {id: 'js-libraries', weight: 0, group: 'best-practices-general'},
        {id: 'deprecations', weight: 5, group: 'best-practices-general'},
        {
          id: 'third-party-cookies',
          weight: 5,
          group: 'best-practices-general',
        },
        {id: 'errors-in-console', weight: 1, group: 'best-practices-general'},
        {id: 'valid-source-maps', weight: 0, group: 'best-practices-general'},
        {id: 'inspector-issues', weight: 1, group: 'best-practices-general'},
      ],
    },
  },
};
